# The version should be in the form X.Y, where X denotes major infrastructural change to how blas is managed,
# and Y denoting blas priority. Currently Y=0 not default, Y=1 default blas.
{% set Y = 1 if blas_impl == 'openblas' else 0 %}
package:
  name: feature_blas
  version: 1.{{ Y }}

build:
  # We mustn't use the build number in the blas package - because we are defining the string,
  # manually we would not be producing unique filenames.
  number: 0
  string: {{ blas_impl }}
  track_features:
    # The "blas" package must always track a feature, else it will be
    # prioritised over all others.
    - feature_blas_{{ blas_impl }}

{% if blas_impl != "noblas" %}
requirements:
  run:
    - {{ blas_impl }}
{% endif %}

test: {}

extra:
  recipe-maintainers:
    - v-turin
